if (System.getenv("ANDROID_RELEASE_STORE_FILE")) {
    android.signingConfigs.create("release") {
        storeFile file(System.getenv("ANDROID_RELEASE_STORE_FILE"))
        storePassword System.getenv("ANDROID_RELEASE_STORE_PASSWORD")
        keyAlias System.getenv("ANDROID_RELEASE_KEY_ALIAS")
        keyPassword System.getenv("ANDROID_RELEASE_KEY_PASSWORD")
    }
    android.buildTypes.release.signingConfig = android.signingConfigs.release
}
